#!/usr/bin/env python
import sys
import os
def rel(x):
	return os.path.join(os.path.abspath(os.path.dirname(__file__)), x)

# This is just temporary
sys.path.append(os.path.join(os.path.abspath(os.path.dirname(__file__)), ".."))

from packer.shell import main

if __name__ == '__main__':
	main()

